{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-triebeard
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/triebeard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/triebeard/triebeard_{{ version }}.tar.gz
  sha256: bf1dd6209cea1aab24e21a85375ca473ad11c2eff400d65c6202c0fb4ef91ec3

build:
  merge_build_host: True  # [win]
  number: 1005
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('triebeard')"           # [not win]
    - "\"%R%\" -e \"library('triebeard')\""  # [win]

about:
  home: https://github.com/Ironholds/triebeard/
  license: MIT
  summary: '''Radix trees'', or ''tries'', are key-value data structures optimised for efficient
    lookups, similar in purpose to hash tables. ''triebeard'' provides an implementation
    of ''radix trees'' for use in R programming and in developing packages with ''Rcpp''.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler
    - ocefpaf

# Package: triebeard
# Type: Package
# Title: 'Radix' Trees in 'Rcpp'
# Version: 0.3.0
# Author: Oliver Keyes [aut, cre], Drew Schmidt [aut], Yuuki Takano [cph]
# Maintainer: Oliver Keyes <ironholds@gmail.com>
# Description: 'Radix trees', or 'tries', are key-value data structures optimised for efficient lookups, similar in purpose to hash tables. 'triebeard' provides an implementation of 'radix trees' for use in R programming and in developing packages with 'Rcpp'.
# License: MIT + file LICENSE
# LazyData: TRUE
# LinkingTo: Rcpp
# Imports: Rcpp
# RoxygenNote: 5.0.1
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# URL: https://github.com/Ironholds/triebeard/
# BugReports: https://github.com/Ironholds/triebeard/issues
# Date: 2016-08-03
# NeedsCompilation: yes
# Packaged: 2016-08-03 21:32:42 UTC; ironholds
# Repository: CRAN
# Date/Publication: 2016-08-04 00:57:37
