appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: EXA7WFvJkzajjaTiKN4Huh7bahWISVyV6mBsjCnQCh1AETKYDgHz7f1scUje8FyomNXYT0pCkgyIzQoagmoaLm6+QRLUH/LJm0NZ6LBAttTmLpKrJJEclQ9sQ22aGZ2GocRojoxpjSOZpXQDPvBSoh0a9tkH5DU1Kw8x08Utxc/mve0+0H3Eh2jg5KQ2pHHDepKMEom/kMcVhotdQkKpmg+HE2v3TAqzRA54eW/+esSQnxk/EZ18WOR7sBk8wThHKRijEVtF1OIG5eeANEmpDJzsblB4pkEAIDP4NH/bJLUaPoh66tIDSMz6OtVUvphEYQyl+r6j1UM/QxA4dass9KuDa/PzoMYlgz0TtuWa82I7AFI1tUYZSAdqnS/D5O/7ubCF5sGBgvbEuJVt0vmaJae5xjV0b9Njefjr0eFZlmaTh4GzVYWlv7b/lS03GvCmGT6gbn5d2GOXAEilcEz28YZu+0BfMFLDRpWmPp5hQ6+4vSc4g++txhAzaXNXDR9uKYBInecLNSVAdV9ifoPyt8XqpvkrqVvi6mJnR3wXFH/DTMzFNVysSrWpEh19AoJIC+HDxmBb8ob8BevtUIfzCtxbtmknVOqB/379PrD/gfIMPSZ7GQg+BG2IpeDqK4N8oythfZ6fUGNfxyAqelT6C5zrIKxW0t9y7rPB3Anz3xE=
